### ISSUE TITLE
Crash if asked to replace a value which can be NULL

### ISSUE THREAD

**Issue by PatrickLerner** [humanmade/go-anonymize-mysqldump#6]
Given a database like

```sql
DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
`email` varchar(255),
);
INSERT INTO `test` VALUES ('foo'), (NULL), ('hodger');
```

if you use a config like

```json
{
  "patterns": [
    {
      "tableName": "test",
      "fields": [
        {
          "field": "email",
          "position": 1,
          "type": "email",
          "constraints": null
        }
      ]
    }
  ]
}
```

the tool will crash with a panic:

```
panic: interface conversion: sqlparser.Expr is *sqlparser.NullVal, not *sqlparser.SQLVal

goroutine 35 [running]:
main.modifyValues(0xc0003f6060, 0x3, 0x4, 0xc00008e2f8, 0x4, 0xc0001e6000, 0x1, 0x4, 0x0, 0x0, ...)
	/Users/aang/Code/golang/src/github.com/humanmade/go-anonymize-mysqldump/anonymize-mysqldump.go:299 +0x572
main.applyConfigToInserts(0xc00041a0b0, 0xc0001e4000, 0x1, 0x4, 0x0, 0x0, 0x0)
	/Users/aang/Code/golang/src/github.com/humanmade/go-anonymize-mysqldump/anonymize-mysqldump.go:277 +0x1f9
main.applyConfigToParsedLine(0x126f020, 0xc00041a0b0, 0xc0001e4000, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0)
	/Users/aang/Code/golang/src/github.com/humanmade/go-anonymize-mysqldump/anonymize-mysqldump.go:250 +0x68
main.processLine(0xc0001cc1c0, 0x36, 0xc0001e4000, 0x1, 0x4, 0x0, 0x0)
	/Users/aang/Code/golang/src/github.com/humanmade/go-anonymize-mysqldump/anonymize-mysqldump.go:218 +0x2c1
main.processInput.func1(0xc00008e320, 0xc0001e4000, 0x1, 0x4, 0xc0003f20c0, 0xc0001cc1c0, 0x36)
	/Users/aang/Code/golang/src/github.com/humanmade/go-anonymize-mysqldump/anonymize-mysqldump.go:194 +0xab
created by main.processInput
	/Users/aang/Code/golang/src/github.com/humanmade/go-anonymize-mysqldump/anonymize-mysqldump.go:192 +0x41c
```

If `NULL` does not appear, it works fine.

**Comment by NikolaiGulatz** [comment]
@PatrickLerner please see my PR which fixes this issue by ignoring NULL values in transformable fields.

**Comment by jasperoosthoek** [comment]
I'm running into this issue right now and would appreciate if this PR gets merged!

**Comment by fadiadawi** [comment]
I used this PR and still getting the same error

**Comment by PatrickLerner** [comment]
Hey @fadiadawi,

When I compiled the binary from Nikolai's branch, I did it like so:

```
docker run -e GOOS=linux -e GOARCH=amd64 -v /tmp/crosstest:/go/bin golang bash -c "git clone 'https://github.com/NikolaiGulatz/go-anonymize-mysqldump.git' /go/src/go-anonymize-mysqldump && cd /go/src/go-anonymize-mysqldump && git checkout fix-for-null-values && go get . && go build"
```

I think the issue is that go does not check out the feature branch? I also remember that this was explicitly not a feature in go to build it from a branch for some reason or another (I don't use go usually).

Hope it helps 🤞

**Comment by fadiadawi** [comment]
Hello and thank you for your reply.
I am trying to run this command on my mac (host) . I tried:

GOOS=linux -e GOARCH=amd64 -v git clone
'https://github.com/NikolaiGulatz/go-anonymize-mysqldump.git'
/go/src/go-anonymize-mysqldump && cd /go/src/go-anonymize-mysqldump &&
git checkout fix-for-null-values && go get . && go build but did not
work. I also removed -r and -v and built a file but when I tried to
run it I got an error saying that the file has incorrect format

**Comment by PatrickLerner** [comment]
Are you trying to run a linux binary on mac?

Maybe try this or similar:

```
docker run -e GOOS=darwin -e GOARCH=amd64 -v /tmp/crosstest:/go/bin golang bash -c "git clone 'https://github.com/NikolaiGulatz/go-anonymize-mysqldump.git' /go/src/go-anonymize-mysqldump && cd /go/src/go-anonymize-mysqldump && git checkout fix-for-null-values && go get . && go build"
```

if you need a mac binary :)

**Comment by fadiadawi** [comment]
I tried but when I attempt to execute the file, I get this error: "cannot
execute binary file: Exec format error"

**Comment by fadiadawi** [comment]
I got it to work using a different approach. I forked the fix and created
my own repo on GitHub. I was then able to build successfully using this
: GOOS=linux GOARCH=amd64  go build -v
github.com/my_user_name/go-anonymize-mysqldump
I am not a GO coder. Thank you for all the help. I really appreciate it :)
